### ISSUE TITLE
Don't throw an error to user when Replay is duplicated

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-replay#338] opened 2022-12-13 14:39 UTC
```
Error: Multiple Sentry Session Replay instances are not supported
```
I just spotted an exception when I called `new Replay();`

It seems to be being generated here https://github.com/getsentry/sentry-replay/blob/main/src/index.ts#L217

Ideally it should use `logger.error` instead of throwing an exception to the user code.

repro?
```
const replay = new Replay();
replay.start();
const replay2 = new Replay();
```

**Comment by mydea** [comment] 2022-12-14 07:48
I think the question is what is supposed to happen in such a case. if we don't throw there, should we start multiple recordings? Some of this is global state which _will_ lead to problems (duplicated event handlers, ...). So IMHO it is correct to error out here, as it is important for the user to _not_ do this, as otherwise there will be a lot of weird problems (duplicate replays, ...). What's the use case to initialize multiple replays?

Also note that `logger.error()` stuff will not be seen by users unless they enable `debug: true`, so user may not even notice something is wrong.

**Comment by bruno-garcia** [comment] 2022-12-14 13:51
> What's the use case to initialize multiple replays?

IMHO there isn't one and it's a user error

> Also note that logger.error() stuff will not be seen by users unless they enable debug: true, so user may not even notice something is wrong.

Since it already logs out, we give the tools users need to debug if something odd is happening. 

So closing this as 'by design'

**Closed as completed by bruno-garcia** 2022-12-14 13:51 UTC
